### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by edumaciel10** [Open-Pix/php-sdk#10]
- [x] #4 
- [x] #3 
- [x] #13 
- [x] #7 
- [x] #6 
- [x] #5 
- [x] #8 
- [x] #23
- [x] #26 
- [ ] Add PHP-SDK examples on Rest API documentation
- [x] #24
- [x] #25

**Comment by criskell** [comment]
mvp released: https://packagist.org/packages/open-pix/php-sdk
